### PR TITLE
Fixes #212 Updated url of CountryInstituteAPI 

### LINKED ISSUE #212: CountryInstituteAPI is not fetching country and institute data on edit profile page.
**Describe the bug**
CountryInstituteAPI is not fetching country data on the edit profile page.

**To Reproduce**

1. Go to 'Profile page'
2. Click on 'edit profile'
3. Entry country name

**Expected behavior**
It should load a list of counties.

**Screenshots**

**Are you working on this issue? (Yes/No)**
**Yes**

### PR DESCRIPTION
**Pull request by noman2002**
Fixes #212 

Describe the changes you have made in this PR -
Updated URL of CountryInstituteAPI which is not loading earlier.

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

### CODE REVIEW

File: lib/services/API/country_institute_api.dart [hunk 1]
```diff
@@ -50,7 +50,7 @@ class HttpCountryInstituteAPI implements CountryInstituteAPI {
 
   @override
   Future<dynamic> getInstitutes(String query) async {
-    var url = 'http://universities.hipolabs.com/search?';
+    var url = 'http://universities.hipolabs.com/search?name=$query';
```
Comment (tachyons) [inline lib/services/API/country_institute_api.dart:53]: Doesn't this duplicate the query, update _fetchAPI method if parameter format is changed

**Review by manjotsidhu — APPROVED** [review]
